# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 368f56c7add6db1016b9ad9538d38bb53ce6ba29e028726aa72bbe8b80bee3617c74ec0d632da465760872276755ef1c2f8b66e75d14362c7816402e72a4048d

test:
  secret_key_base: 42f8e802b3d062efad37a0ca120faf0bcf899a807847de3cdcb863d93ed7dd902d9a1608a0a3883a078d5c85db7ff851b95f4a4b634a7ba3ca90f690eb7ce838

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
